- name: Deploy a web application
  hosts: db_and_web_server*
  tasks:
    - name: Install required dependencies
      apt: 
        name: ['python', 'python-setuptools', 'python-dev', 'build-essential', 'python-pip', 'python-mysqldb'] 
        state: present

    - name: Install mysql database
      apt: 
        name: ['mysql-server', 'mysql-client'] 
        state: present

    - name: start database
      service: 
        name: mysql
        state: started
        enabled: yes

    - name: create database
      mysql_db: name={{ db_name }} state=present
    
    - name: create database user
      mysql_user: 
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        priv: '*.*:All'
        state: present
        host: '%'

    - name: export env variable
      shell: export LC_ALL=C

    - name: install Flask  dependencies
      pip:
        name: ['flask', 'flask-mysql']
        state: present

    - name: copy app
      copy: src=app.py dest=/opt/app.py

    - name: start webserver
      shell: FLASK_APP=/opt/app.py nohup flask run --host=0.0.0.0 &

  vars:
    db_name: employee_db
    db_user: db_user
    db_password: Passw0rd